name: ci

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SELENIUM_RELEASE: ["4.0.0"]
        NODE_RELEASE: ["12.22.9", "14.18.3", "16.13.2"]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            NODE_RELEASE=${{ matrix.NODE_RELEASE }}
            SELENIUM_RELEASE=${{ matrix.SELENIUM_RELEASE }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node:${{ matrix.NODE_RELEASE }}-selenium${{ matrix.SELENIUM_RELEASE }}
