name: ci

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SELENIUM_RELEASE: ["4.6.0"]
        NODE_RELEASE: ["18.12.1", "16.18.1", "14.21.1"]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            SELENIUM_RELEASE=${{ matrix.SELENIUM_RELEASE }}
            NODE_RELEASE=${{ matrix.NODE_RELEASE }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node:${{ matrix.NODE_RELEASE }}-selenium${{ matrix.SELENIUM_RELEASE }}
